development:
  adapter: postgresql
  encoding: unicode
  database: westendathletic_development
  pool: 5
  min_messages: warning
  username: Matt
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: westendathletic_test
  pool: 5
  min_messages: warning
  username: Matt
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: westendathletic_production
  pool: 5
  username: Matt
  password: